name: Continuous Integration

on:
  pull_request:
    branches:
      - main

jobs:

  test:

    name: Test
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Repo
        uses: actions/checkout@v2.3.1

      - uses: actions/cache@v2
        id: cache
        with:
          path: node_modules
          key: ${{ runner.os }}-node-${{ hashFiles('**/package.json') }}
          restore-keys: |
            ${{ runner.os }}-node-
      
      - name: Install Node Modules
        if: steps.cache.outputs.cache-hit != 'true'
        run: npm install --legacy-peer-deps

      - name: Run Tests
        run: npm test
        env:
          AUTH_KEY: "Hello World"
          MONGO_URI: ${{ secrets.MONGO_URI }}
          PASSWORD_KEY: "PASSWORD"